/**
 * Reddit Strategy Spreadsheet Builder
 *
 * Generates a client-presentable XLSX with:
 *   1. Executive Summary
 *   2. Threads & Comments (combined)
 *   3. Post Drafts
 *   4. Upvote Plan
 *   5. Reporting Tracker
 */

const ExcelJS = require('exceljs');

// ── Color Palette ──
const COLORS = {
  headerBg:    'FF1A1A2E',  // Dark navy
  headerFont:  'FFFFFFFF',
  accentBg:    'FF16213E',  // Slightly lighter navy
  accentFont:  'FFFFFFFF',
  highBg:      'FFD4EDDA',  // Light green
  medBg:       'FFFFF3CD',  // Light yellow
  lowBg:       'FFF8D7DA',  // Light red
  accentPurple: 'FF6C5CE7',  // Brand accent
  lightGray:   'FFF8F9FA',
  borderColor: 'FFE0E0E0',
};

function applyHeaderStyle(row, colCount) {
  for (let c = 1; c <= colCount; c++) {
    const cell = row.getCell(c);
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.headerBg } };
    cell.font = { bold: true, color: { argb: COLORS.headerFont }, size: 11, name: 'Calibri' };
    cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
    cell.border = {
      bottom: { style: 'medium', color: { argb: COLORS.accentPurple } },
    };
  }
  row.height = 28;
}

function applyDataStyle(row, colCount, isAlt) {
  for (let c = 1; c <= colCount; c++) {
    const cell = row.getCell(c);
    if (isAlt) {
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.lightGray } };
    }
    cell.font = { size: 10, name: 'Calibri' };
    cell.alignment = { vertical: 'top', wrapText: true };
    cell.border = {
      bottom: { style: 'thin', color: { argb: COLORS.borderColor } },
    };
  }
}

function setScoreColor(cell, score) {
  if (score >= 70) {
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.highBg } };
  } else if (score >= 40) {
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.medBg } };
  } else {
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.lowBg } };
  }
}

/**
 * Build the complete strategy spreadsheet.
 *
 * @param {object} strategyData - Full pipeline output
 * @param {object} brandProfile - Brand profile
 * @param {string} packageTier - Package tier key
 * @param {object} formData - Form inputs (month, prevSpreadsheetUrl, etc.)
 * @returns {Buffer} XLSX file as a buffer
 */
async function buildStrategySpreadsheet(strategyData, brandProfile, packageTier, formData = {}) {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'George Reddit Bot';
  wb.created = new Date();

  const clientName = brandProfile.clientName || 'Client';
  const report = strategyData.report || {};
  const month = formData.month || '1';
  const monthNum = parseInt(month) || 1;
  const monthLabel = `Month ${month}`;
  // Tab names are always the same — month data is distinguished by the Month column + separator rows
  const tabPrefix = '';

  // ═══════════════════════════════════════════
  // Sheet 1: Executive Summary
  // ═══════════════════════════════════════════
  const summarySheet = wb.addWorksheet(`${tabPrefix}Executive Summary`, {
    properties: { tabColor: { argb: COLORS.accentPurple } },
  });
  summarySheet.columns = [
    { width: 3 },   // A spacer
    { width: 25 },  // B label
    { width: 65 },  // C value
    { width: 3 },   // D spacer
  ];

  // Title row
  summarySheet.mergeCells('B2:C2');
  const titleCell = summarySheet.getCell('B2');
  titleCell.value = `Reddit Strategy Report — ${clientName}`;
  titleCell.font = { bold: true, size: 18, color: { argb: COLORS.headerBg }, name: 'Calibri' };
  titleCell.alignment = { horizontal: 'left' };

  // Subtitle
  summarySheet.mergeCells('B3:C3');
  const subCell = summarySheet.getCell('B3');
  subCell.value = `${monthLabel} | Generated by George Reddit Bot | ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`;
  subCell.font = { size: 10, italic: true, color: { argb: 'FF888888' }, name: 'Calibri' };

  const comments = strategyData.commentsWithAlignment || [];
  const posts = strategyData.posts || [];

  // Summary fields
  const summaryRows = [
    ['Package', formData.packageName || packageTier],
    ['Keywords Researched', (strategyData.keywords || []).join(', ')],
    ['Threads Discovered', String(strategyData.threads?.length || 0)],
    ['Comments Drafted', String(comments.length)],
    ['Posts Drafted', String(posts.length)],
    ['Campaign Month', monthLabel],
    ['', ''],
    ['Executive Summary', report.executiveSummary || 'N/A'],
  ];

  let sr = 5;
  for (const [label, val] of summaryRows) {
    const row = summarySheet.getRow(sr);
    row.getCell(2).value = label;
    row.getCell(2).font = { bold: true, size: 11, name: 'Calibri' };
    row.getCell(3).value = val;
    row.getCell(3).font = { size: 11, name: 'Calibri' };
    row.getCell(3).alignment = { wrapText: true };
    sr++;
  }

  // Risk Assessment
  sr += 1;
  summarySheet.getRow(sr).getCell(2).value = 'Risk Level';
  summarySheet.getRow(sr).getCell(2).font = { bold: true, size: 11, name: 'Calibri' };
  summarySheet.getRow(sr).getCell(3).value = (report.riskAssessment?.overallRisk || 'unknown').toUpperCase();
  summarySheet.getRow(sr).getCell(3).font = { bold: true, size: 11, name: 'Calibri' };
  const riskCell = summarySheet.getRow(sr).getCell(3);
  if (report.riskAssessment?.overallRisk === 'high') riskCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.lowBg } };
  else if (report.riskAssessment?.overallRisk === 'medium') riskCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.medBg } };
  else riskCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.highBg } };

  // Recommended Actions
  sr += 2;
  summarySheet.mergeCells(`B${sr}:C${sr}`);
  summarySheet.getRow(sr).getCell(2).value = 'Recommended Actions';
  summarySheet.getRow(sr).getCell(2).font = { bold: true, size: 14, color: { argb: COLORS.headerBg }, name: 'Calibri' };
  sr++;

  const actHeader = summarySheet.getRow(sr);
  actHeader.getCell(2).value = 'Action';
  actHeader.getCell(3).value = 'Priority / Timeline';
  applyHeaderStyle(actHeader, 3);

  for (const act of (report.recommendedActions || []).slice(0, 8)) {
    sr++;
    const row = summarySheet.getRow(sr);
    row.getCell(2).value = act.action;
    row.getCell(2).font = { size: 10, name: 'Calibri' };
    row.getCell(2).alignment = { wrapText: true };
    row.getCell(3).value = `${(act.priority || '').toUpperCase()} — ${act.timeline || 'TBD'}`;
    row.getCell(3).font = { size: 10, name: 'Calibri' };
  }

  // ═══════════════════════════════════════════
  // Sheet 2: Threads & Comments (combined)
  // ═══════════════════════════════════════════
  const tcSheet = wb.addWorksheet(`${tabPrefix}Threads & Comments`, {
    properties: { tabColor: { argb: 'FF00B894' } },
  });

  const tcCols = ['#', 'Month', 'Type', 'Subreddit', 'Thread Title', 'Thread URL', 'Category/Angle',
    'Score', 'Comment/Opportunity Text', 'Brand Mention', 'Spam Risk', 'Status', 'Comment/Post Link', 'Posting Date', 'Notes'];
  tcSheet.columns = [
    { width: 5 },   // #
    { width: 12 },  // Month
    { width: 10 },  // Type
    { width: 18 },  // Subreddit
    { width: 40 },  // Thread Title
    { width: 50 },  // URL
    { width: 20 },  // Category/Angle
    { width: 10 },  // Score
    { width: 70 },  // Comment/Opportunity
    { width: 14 },  // Brand Mention
    { width: 10 },  // Spam Risk
    { width: 14 },  // Status
    { width: 40 },  // Comment/Post Link
    { width: 14 },  // Posting Date
    { width: 30 },  // Notes
  ];

  const tcHeader = tcSheet.addRow(tcCols);
  applyHeaderStyle(tcHeader, tcCols.length);

  // Add threads first
  const analyzedThreads = strategyData.threadAnalysis?.analyzedThreads || [];
  analyzedThreads.forEach((t, i) => {
    const row = tcSheet.addRow([
      i + 1,
      monthLabel,
      'THREAD',
      t.subreddit || '',
      t.title || '',
      t.url || '',
      (t.category || '').replace('_', ' ').toUpperCase(),
      t.overallScore || 0,
      t.opportunity || '',
      '',
      '',
      '',
      '',
      '',
      t.suggestedAngle || '',
    ]);
    applyDataStyle(row, tcCols.length, false);
    if (t.overallScore) setScoreColor(row.getCell(8), t.overallScore);

    const catCell = row.getCell(7);
    if (t.category === 'high_value') catCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.highBg } };
    else if (t.category === 'medium_value') catCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.medBg } };
    else catCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.lowBg } };
  });

  // Add comments
  comments.forEach((c, i) => {
    const a = c.alignment || {};
    const row = tcSheet.addRow([
      analyzedThreads.length + i + 1,
      monthLabel,
      'COMMENT',
      c.subreddit || '',
      c.threadTitle || '',
      c.threadUrl || '',
      c.angle || '',
      a.score || 0,
      c.comment || '',
      c.brandMentionType || '',
      a.spamRisk || '',
      'Pending Review',
      '',
      '',
      (a.issues || []).join('; '),
    ]);
    applyDataStyle(row, tcCols.length, i % 2 === 1);
    if (a.score) setScoreColor(row.getCell(8), a.score);

    const spamCell = row.getCell(11);
    if (a.spamRisk === 'high') spamCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.lowBg } };
    else if (a.spamRisk === 'medium') spamCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.medBg } };
    else spamCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.highBg } };
  });

  const totalTcRows = analyzedThreads.length + comments.length;
  if (totalTcRows > 0) {
    tcSheet.autoFilter = { from: 'A1', to: `O${totalTcRows + 1}` };
  }

  // ═══════════════════════════════════════════
  // Sheet 3: Post Drafts
  // ═══════════════════════════════════════════
  const postSheet = wb.addWorksheet(`${tabPrefix}Post Drafts`, {
    properties: { tabColor: { argb: 'FF00CEC9' } },
  });

  const postCols = ['#', 'Month', 'Subreddit', 'Post Type', 'Title', 'Post Body',
    'Follow-Up Comment', 'Brand Mention Strategy', 'Engagement Potential', 'Status', 'Post Link', 'Posting Date', 'Notes'];
  postSheet.columns = [
    { width: 5 },   // #
    { width: 12 },  // Month
    { width: 18 },  // Subreddit
    { width: 14 },  // Post Type
    { width: 40 },  // Title
    { width: 70 },  // Body
    { width: 60 },  // Follow-Up Comment
    { width: 40 },  // Brand Strategy
    { width: 14 },  // Engagement
    { width: 14 },  // Status
    { width: 40 },  // Post Link
    { width: 14 },  // Posting Date
    { width: 30 },  // Notes
  ];

  const postHeader = postSheet.addRow(postCols);
  applyHeaderStyle(postHeader, postCols.length);

  posts.forEach((p, i) => {
    const row = postSheet.addRow([
      i + 1,
      monthLabel,
      p.subreddit || '',
      p.postType || '',
      p.title || '',
      p.body || '',
      p.followUpComment || '',
      p.brandMentionStrategy || '',
      p.engagementPotential || '',
      'Pending Review',
      '',
      '',
      '',
    ]);
    applyDataStyle(row, postCols.length, i % 2 === 1);
  });

  if (posts.length === 0) {
    const noPostRow = postSheet.addRow([
      '', '', '', '', 'No posts included in this package tier', '', '', '', '', '', '', '', '',
    ]);
    applyDataStyle(noPostRow, postCols.length, false);
    noPostRow.getCell(5).font = { italic: true, size: 10, name: 'Calibri', color: { argb: 'FF888888' } };
  }

  // ═══════════════════════════════════════════
  // Sheet 4: Upvote Plan
  // ═══════════════════════════════════════════
  const upvoteSheet = wb.addWorksheet(`${tabPrefix}Upvote Plan`, {
    properties: { tabColor: { argb: 'FFE17055' } },
  });

  const upvoteCols = ['#', 'Content Type', 'Target', 'Subreddit', 'Upvotes Allocated', 'Timing', 'Priority', 'Notes'];
  upvoteSheet.columns = [
    { width: 5 },
    { width: 14 },
    { width: 45 },
    { width: 18 },
    { width: 16 },
    { width: 25 },
    { width: 12 },
    { width: 35 },
  ];

  const upHeader = upvoteSheet.addRow(upvoteCols);
  applyHeaderStyle(upHeader, upvoteCols.length);

  const upvotePlan = strategyData.upvotePlan;
  if (upvotePlan?.distribution?.length > 0) {
    upvotePlan.distribution.forEach((item, i) => {
      const row = upvoteSheet.addRow([
        i + 1,
        item.contentType || item.type || '',
        item.target || '',
        item.subreddit || '',
        item.upvotes || 0,
        item.timing || '',
        (item.priority || '').toUpperCase(),
        item.notes || '',
      ]);
      applyDataStyle(row, upvoteCols.length, i % 2 === 1);
    });

    // Summary row
    const sumRow = upvoteSheet.addRow([
      '', '', 'TOTAL', '', upvotePlan.totalUpvotes || 0, '', '', '',
    ]);
    sumRow.getCell(3).font = { bold: true, size: 11, name: 'Calibri' };
    sumRow.getCell(5).font = { bold: true, size: 11, name: 'Calibri' };
  } else {
    const noUpRow = upvoteSheet.addRow([
      '', '', 'Upvote support not included in this package tier', '', '', '', '', '',
    ]);
    applyDataStyle(noUpRow, upvoteCols.length, false);
    noUpRow.getCell(3).font = { italic: true, size: 10, name: 'Calibri', color: { argb: 'FF888888' } };
  }

  // ═══════════════════════════════════════════
  // Sheet 5: Reporting Tracker
  // ═══════════════════════════════════════════
  const trackerSheet = wb.addWorksheet(`${tabPrefix}Reporting Tracker`, {
    properties: { tabColor: { argb: 'FFE84393' } },
  });

  const trackerCols = ['Month', 'Keywords', 'Threads Found',
    'Comments Drafted', 'Comments Posted',
    'Posts Drafted', 'Posts Published', 'Upvotes Used',
    'Risk Level', 'Notes'];
  trackerSheet.columns = [
    { width: 12 },
    { width: 14 },
    { width: 14 },
    { width: 14 },
    { width: 14 },
    { width: 14 },
    { width: 14 },
    { width: 12 },
    { width: 12 },
    { width: 35 },
  ];

  const trHeader = trackerSheet.addRow(trackerCols);
  applyHeaderStyle(trHeader, trackerCols.length);

  // If month > 1, add placeholder rows for previous months
  for (let m = 1; m < monthNum; m++) {
    const prevRow = trackerSheet.addRow([
      `Month ${m}`,
      '', '', '', '', '', '', '', '',
      formData.prevSpreadsheetUrl ? `See previous report: ${formData.prevSpreadsheetUrl}` : 'Data from previous period',
    ]);
    applyDataStyle(prevRow, trackerCols.length, false);
    prevRow.getCell(1).font = { bold: true, size: 10, name: 'Calibri', color: { argb: 'FF888888' } };
  }

  // Current month row
  const currentRow = trackerSheet.addRow([
    monthLabel,
    String(strategyData.keywords?.length || 0),
    String(strategyData.threads?.length || 0),
    String(comments.length),
    '0',  // Posted — filled in after execution
    String(posts.length),
    '0',  // Posts published — filled in after execution
    String(upvotePlan?.totalUpvotes || 0),
    (report.riskAssessment?.overallRisk || 'unknown').toUpperCase(),
    'Update after execution',
  ]);
  applyDataStyle(currentRow, trackerCols.length, false);
  currentRow.getCell(1).font = { bold: true, size: 11, name: 'Calibri' };
  currentRow.getCell(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE8F4FD' } };

  // Generate buffer
  const buffer = await wb.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

module.exports = { buildStrategySpreadsheet };
