/**
 * Reddit Strategy Spreadsheet Builder
 *
 * Generates a client-presentable XLSX with:
 *   1. Executive Summary sheet
 *   2. Thread Discovery sheet — all discovered threads with scores
 *   3. Comment Drafts sheet — each comment with thread details, alignment
 *   4. Subreddit Strategy sheet — approach per subreddit
 *   5. Reporting Tracker sheet — for month-over-month tracking
 */

const ExcelJS = require('exceljs');

// ── Color Palette ──
const COLORS = {
  headerBg:    'FF1A1A2E',  // Dark navy
  headerFont:  'FFFFFFFF',
  accentBg:    'FF16213E',  // Slightly lighter navy
  accentFont:  'FFFFFFFF',
  highBg:      'FFD4EDDA',  // Light green
  medBg:       'FFFFF3CD',  // Light yellow
  lowBg:       'FFF8D7DA',  // Light red
  accentPurple: 'FF6C5CE7',  // Brand accent
  lightGray:   'FFF8F9FA',
  borderColor: 'FFE0E0E0',
};

function applyHeaderStyle(row, colCount) {
  for (let c = 1; c <= colCount; c++) {
    const cell = row.getCell(c);
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.headerBg } };
    cell.font = { bold: true, color: { argb: COLORS.headerFont }, size: 11, name: 'Calibri' };
    cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
    cell.border = {
      bottom: { style: 'medium', color: { argb: COLORS.accentPurple } },
    };
  }
  row.height = 28;
}

function applyDataStyle(row, colCount, isAlt) {
  for (let c = 1; c <= colCount; c++) {
    const cell = row.getCell(c);
    if (isAlt) {
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.lightGray } };
    }
    cell.font = { size: 10, name: 'Calibri' };
    cell.alignment = { vertical: 'top', wrapText: true };
    cell.border = {
      bottom: { style: 'thin', color: { argb: COLORS.borderColor } },
    };
  }
}

function setScoreColor(cell, score) {
  if (score >= 70) {
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.highBg } };
  } else if (score >= 40) {
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.medBg } };
  } else {
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.lowBg } };
  }
}

/**
 * Build the complete strategy spreadsheet.
 *
 * @param {object} strategyData - Full pipeline output
 * @param {object} brandProfile - Brand profile
 * @param {string} packageTier - Package tier key
 * @param {object} formData - Form inputs (month, prevSpreadsheetUrl, etc.)
 * @returns {Buffer} XLSX file as a buffer
 */
async function buildStrategySpreadsheet(strategyData, brandProfile, packageTier, formData = {}) {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'George Reddit Bot';
  wb.created = new Date();

  const clientName = brandProfile.clientName || 'Client';
  const report = strategyData.report || {};
  const month = formData.month || '1';
  const monthLabel = `Month ${month}`;

  // ═══════════════════════════════════════════
  // Sheet 1: Executive Summary
  // ═══════════════════════════════════════════
  const summarySheet = wb.addWorksheet('Executive Summary', {
    properties: { tabColor: { argb: COLORS.accentPurple } },
  });
  summarySheet.columns = [
    { width: 3 },   // A spacer
    { width: 25 },  // B label
    { width: 65 },  // C value
    { width: 3 },   // D spacer
  ];

  // Title row
  summarySheet.mergeCells('B2:C2');
  const titleCell = summarySheet.getCell('B2');
  titleCell.value = `Reddit Strategy Report — ${clientName}`;
  titleCell.font = { bold: true, size: 18, color: { argb: COLORS.headerBg }, name: 'Calibri' };
  titleCell.alignment = { horizontal: 'left' };

  // Subtitle
  summarySheet.mergeCells('B3:C3');
  const subCell = summarySheet.getCell('B3');
  subCell.value = `${monthLabel} | Generated by George Reddit Bot | ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`;
  subCell.font = { size: 10, italic: true, color: { argb: 'FF888888' }, name: 'Calibri' };

  // Summary fields
  const summaryRows = [
    ['Package', formData.packageName || packageTier],
    ['Keywords Researched', (strategyData.keywords || []).join(', ')],
    ['Threads Discovered', String(strategyData.threads?.length || 0)],
    ['Comments Drafted', String(strategyData.commentsWithAlignment?.length || 0)],
    ['Campaign Month', monthLabel],
    ['', ''],
    ['Executive Summary', report.executiveSummary || 'N/A'],
  ];

  let sr = 5;
  for (const [label, val] of summaryRows) {
    const row = summarySheet.getRow(sr);
    row.getCell(2).value = label;
    row.getCell(2).font = { bold: true, size: 11, name: 'Calibri' };
    row.getCell(3).value = val;
    row.getCell(3).font = { size: 11, name: 'Calibri' };
    row.getCell(3).alignment = { wrapText: true };
    sr++;
  }

  // Risk Assessment
  sr += 1;
  summarySheet.getRow(sr).getCell(2).value = 'Risk Level';
  summarySheet.getRow(sr).getCell(2).font = { bold: true, size: 11, name: 'Calibri' };
  summarySheet.getRow(sr).getCell(3).value = (report.riskAssessment?.overallRisk || 'unknown').toUpperCase();
  summarySheet.getRow(sr).getCell(3).font = { bold: true, size: 11, name: 'Calibri' };
  const riskCell = summarySheet.getRow(sr).getCell(3);
  if (report.riskAssessment?.overallRisk === 'high') riskCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.lowBg } };
  else if (report.riskAssessment?.overallRisk === 'medium') riskCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.medBg } };
  else riskCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.highBg } };

  // Recommended Actions
  sr += 2;
  summarySheet.mergeCells(`B${sr}:C${sr}`);
  summarySheet.getRow(sr).getCell(2).value = 'Recommended Actions';
  summarySheet.getRow(sr).getCell(2).font = { bold: true, size: 14, color: { argb: COLORS.headerBg }, name: 'Calibri' };
  sr++;

  const actHeader = summarySheet.getRow(sr);
  actHeader.getCell(2).value = 'Action';
  actHeader.getCell(3).value = 'Priority / Timeline';
  applyHeaderStyle(actHeader, 3);

  for (const act of (report.recommendedActions || []).slice(0, 8)) {
    sr++;
    const row = summarySheet.getRow(sr);
    row.getCell(2).value = act.action;
    row.getCell(2).font = { size: 10, name: 'Calibri' };
    row.getCell(2).alignment = { wrapText: true };
    row.getCell(3).value = `${(act.priority || '').toUpperCase()} — ${act.timeline || 'TBD'}`;
    row.getCell(3).font = { size: 10, name: 'Calibri' };
  }

  // ═══════════════════════════════════════════
  // Sheet 2: Thread Discovery
  // ═══════════════════════════════════════════
  const threadSheet = wb.addWorksheet('Thread Discovery', {
    properties: { tabColor: { argb: 'FF00B894' } },
  });

  const threadCols = ['#', 'Thread Title', 'Subreddit', 'URL', 'Category', 'Overall Score',
    'Google Rank', 'AI Citation', 'Engagement', 'Opportunity', 'Suggested Angle', 'Matched Keywords'];
  threadSheet.columns = [
    { width: 5 },   // #
    { width: 45 },  // Title
    { width: 18 },  // Subreddit
    { width: 50 },  // URL
    { width: 14 },  // Category
    { width: 12 },  // Score
    { width: 10 },  // Google Rank
    { width: 10 },  // AI Citation
    { width: 10 },  // Engagement
    { width: 12 },  // Opportunity
    { width: 35 },  // Angle
    { width: 30 },  // Keywords
  ];

  const thHeader = threadSheet.addRow(threadCols);
  applyHeaderStyle(thHeader, threadCols.length);

  const analyzedThreads = strategyData.threadAnalysis?.analyzedThreads || [];
  analyzedThreads.forEach((t, i) => {
    const row = threadSheet.addRow([
      i + 1,
      t.title || '',
      t.subreddit || '',
      t.url || '',
      (t.category || '').replace('_', ' ').toUpperCase(),
      t.overallScore || 0,
      t.scores?.googleRanking || '',
      t.scores?.aiCitation || '',
      t.scores?.engagement || '',
      t.scores?.opportunity || '',
      t.suggestedAngle || '',
      (t.matchedKeywords || []).join(', '),
    ]);
    applyDataStyle(row, threadCols.length, i % 2 === 1);

    // Color the score cell
    if (t.overallScore) setScoreColor(row.getCell(6), t.overallScore);

    // Color the category
    const catCell = row.getCell(5);
    if (t.category === 'high_value') catCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.highBg } };
    else if (t.category === 'medium_value') catCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.medBg } };
    else catCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.lowBg } };
  });

  // Auto-filter
  if (analyzedThreads.length > 0) {
    threadSheet.autoFilter = { from: 'A1', to: `L${analyzedThreads.length + 1}` };
  }

  // ═══════════════════════════════════════════
  // Sheet 3: Comment Drafts
  // ═══════════════════════════════════════════
  const commentSheet = wb.addWorksheet('Comment Drafts', {
    properties: { tabColor: { argb: 'FF6C5CE7' } },
  });

  const commentCols = ['#', 'Subreddit', 'Thread Title', 'Thread URL', 'Comment Angle',
    'Comment Text', 'Brand Mention Type', 'Alignment Score', 'Spam Risk',
    'Alignment Issues', 'Status', 'Vendor Notes'];
  commentSheet.columns = [
    { width: 5 },   // #
    { width: 18 },  // Subreddit
    { width: 35 },  // Thread Title
    { width: 50 },  // URL
    { width: 30 },  // Angle
    { width: 70 },  // Comment Text
    { width: 16 },  // Brand Mention Type
    { width: 12 },  // Alignment Score
    { width: 12 },  // Spam Risk
    { width: 35 },  // Issues
    { width: 14 },  // Status
    { width: 30 },  // Vendor Notes
  ];

  const cmHeader = commentSheet.addRow(commentCols);
  applyHeaderStyle(cmHeader, commentCols.length);

  const comments = strategyData.commentsWithAlignment || [];
  comments.forEach((c, i) => {
    const alignment = c.alignment || {};
    const row = commentSheet.addRow([
      i + 1,
      c.subreddit || '',
      c.threadTitle || '',
      c.threadUrl || '',
      c.angle || '',
      c.comment || '',
      c.brandMentionType || '',
      alignment.score || 0,
      alignment.spamRisk || 'unknown',
      (alignment.issues || []).join('; '),
      'Pending Review',
      '',
    ]);
    applyDataStyle(row, commentCols.length, i % 2 === 1);

    // Color alignment score
    if (alignment.score) setScoreColor(row.getCell(8), alignment.score);

    // Color spam risk
    const spamCell = row.getCell(9);
    if (alignment.spamRisk === 'high') spamCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.lowBg } };
    else if (alignment.spamRisk === 'medium') spamCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.medBg } };
    else spamCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.highBg } };
  });

  if (comments.length > 0) {
    commentSheet.autoFilter = { from: 'A1', to: `L${comments.length + 1}` };
  }

  // ═══════════════════════════════════════════
  // Sheet 4: Post Drafts
  // ═══════════════════════════════════════════
  const postSheet = wb.addWorksheet('Post Drafts', {
    properties: { tabColor: { argb: 'FF00CEC9' } },
  });

  const postCols = ['#', 'Subreddit', 'Post Type', 'Title', 'Post Body',
    'Follow-Up Comment', 'Brand Mention Strategy', 'Engagement Potential', 'Status', 'Notes'];
  postSheet.columns = [
    { width: 5 },   // #
    { width: 18 },  // Subreddit
    { width: 14 },  // Post Type
    { width: 40 },  // Title
    { width: 70 },  // Body
    { width: 60 },  // Follow-Up Comment
    { width: 40 },  // Brand Strategy
    { width: 14 },  // Engagement
    { width: 14 },  // Status
    { width: 30 },  // Notes
  ];

  const postHeader = postSheet.addRow(postCols);
  applyHeaderStyle(postHeader, postCols.length);

  const posts = strategyData.posts || [];
  posts.forEach((p, i) => {
    const row = postSheet.addRow([
      i + 1,
      p.subreddit || '',
      p.postType || '',
      p.title || '',
      p.body || '',
      p.followUpComment || '',
      p.brandMentionStrategy || '',
      p.engagementPotential || '',
      'Pending Review',
      '',
    ]);
    applyDataStyle(row, postCols.length, i % 2 === 1);
  });

  if (posts.length === 0) {
    const noPostRow = postSheet.addRow([
      '', '', '', 'No posts included in this package tier', '', '', '', '', '', '',
    ]);
    applyDataStyle(noPostRow, postCols.length, false);
    noPostRow.getCell(4).font = { italic: true, size: 10, name: 'Calibri', color: { argb: 'FF888888' } };
  }

  // ═══════════════════════════════════════════
  // Sheet 5: Upvote Plan
  // ═══════════════════════════════════════════
  const upvoteSheet = wb.addWorksheet('Upvote Plan', {
    properties: { tabColor: { argb: 'FFE17055' } },
  });

  const upvoteCols = ['#', 'Content Type', 'Target', 'Subreddit', 'Upvotes Allocated', 'Timing', 'Priority', 'Notes'];
  upvoteSheet.columns = [
    { width: 5 },
    { width: 14 },
    { width: 45 },
    { width: 18 },
    { width: 16 },
    { width: 25 },
    { width: 12 },
    { width: 35 },
  ];

  const upHeader = upvoteSheet.addRow(upvoteCols);
  applyHeaderStyle(upHeader, upvoteCols.length);

  const upvotePlan = strategyData.upvotePlan;
  if (upvotePlan?.distribution?.length > 0) {
    upvotePlan.distribution.forEach((item, i) => {
      const row = upvoteSheet.addRow([
        i + 1,
        item.contentType || '',
        item.target || '',
        item.subreddit || '',
        item.upvotes || 0,
        item.timing || '',
        (item.priority || '').toUpperCase(),
        item.notes || '',
      ]);
      applyDataStyle(row, upvoteCols.length, i % 2 === 1);
    });

    // Summary row
    const sumRow = upvoteSheet.addRow([
      '', '', 'TOTAL', '', upvotePlan.totalUpvotes || 0, '', '', '',
    ]);
    sumRow.getCell(3).font = { bold: true, size: 11, name: 'Calibri' };
    sumRow.getCell(5).font = { bold: true, size: 11, name: 'Calibri' };
  } else {
    const noUpRow = upvoteSheet.addRow([
      '', '', 'Upvote support not included in this package tier', '', '', '', '', '',
    ]);
    applyDataStyle(noUpRow, upvoteCols.length, false);
    noUpRow.getCell(3).font = { italic: true, size: 10, name: 'Calibri', color: { argb: 'FF888888' } };
  }

  // ═══════════════════════════════════════════
  // Sheet 6: Subreddit Strategy
  // ═══════════════════════════════════════════
  const subSheet = wb.addWorksheet('Subreddit Strategy', {
    properties: { tabColor: { argb: 'FFFDCB6E' } },
  });

  const subCols = ['Subreddit', 'Archetype', 'Priority', 'Thread Count', 'Avg Score', 'Approach'];
  subSheet.columns = [
    { width: 22 },
    { width: 25 },
    { width: 12 },
    { width: 12 },
    { width: 12 },
    { width: 65 },
  ];

  const subHeader = subSheet.addRow(subCols);
  applyHeaderStyle(subHeader, subCols.length);

  // Combine report subredditStrategy with threadAnalysis subredditMap
  const subStrategies = report.subredditStrategy || [];
  const subMap = strategyData.threadAnalysis?.subredditMap || {};

  const allSubs = new Set([
    ...subStrategies.map(s => s.subreddit),
    ...Object.keys(subMap),
  ]);

  let si = 0;
  for (const sub of allSubs) {
    const strat = subStrategies.find(s => s.subreddit === sub) || {};
    const mapData = subMap[sub] || {};

    const row = subSheet.addRow([
      sub,
      strat.archetype || mapData.archetype || '',
      (strat.priority || '').toUpperCase(),
      mapData.threadCount || '',
      mapData.avgScore || '',
      strat.approach || mapData.engagementStrategy || '',
    ]);
    applyDataStyle(row, subCols.length, si % 2 === 1);

    // Color priority
    const prioCell = row.getCell(3);
    if (strat.priority === 'high') prioCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.lowBg } };
    else if (strat.priority === 'medium') prioCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.medBg } };
    else prioCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: COLORS.highBg } };

    si++;
  }

  // NOTE: Brand Alignment data is internal only (used as a guardrail in the pipeline).
  // It is NOT included in the client-facing spreadsheet.

  // ═══════════════════════════════════════════
  // Sheet 7: Reporting Tracker
  // ═══════════════════════════════════════════
  const trackerSheet = wb.addWorksheet('Reporting Tracker', {
    properties: { tabColor: { argb: 'FFE84393' } },
  });

  const trackerCols = ['Month', 'Keywords', 'Threads Found',
    'Comments Drafted', 'Comments Approved', 'Comments Posted',
    'Posts Drafted', 'Posts Published', 'Upvotes Used',
    'Brand Align Score', 'Reddit BP Score', 'Risk Level', 'Notes'];
  trackerSheet.columns = [
    { width: 12 },
    { width: 14 },
    { width: 14 },
    { width: 14 },
    { width: 14 },
    { width: 14 },
    { width: 14 },
    { width: 14 },
    { width: 12 },
    { width: 14 },
    { width: 14 },
    { width: 12 },
    { width: 35 },
  ];

  const trHeader = trackerSheet.addRow(trackerCols);
  applyHeaderStyle(trHeader, trackerCols.length);

  // If month > 1, add placeholder rows for previous months
  const monthNum = parseInt(month) || 1;
  for (let m = 1; m < monthNum; m++) {
    const prevRow = trackerSheet.addRow([
      `Month ${m}`,
      '', '', '', '', '', '', '', '', '', '', '',
      formData.prevSpreadsheetUrl ? `See previous report: ${formData.prevSpreadsheetUrl}` : 'Data from previous period',
    ]);
    applyDataStyle(prevRow, trackerCols.length, false);
    prevRow.getCell(1).font = { bold: true, size: 10, name: 'Calibri', color: { argb: 'FF888888' } };
  }

  // Current month row
  const avgAlignment = comments.length > 0
    ? Math.round(comments.reduce((sum, c) => sum + (c.alignment?.score || 0), 0) / comments.length)
    : 0;
  const brandAlignScore = strategyData.brandAlignmentReport?.overall_score || '—';
  const redditBPScore = strategyData.bestPracticesReport?.overall_score || '—';

  const currentRow = trackerSheet.addRow([
    monthLabel,
    String(strategyData.keywords?.length || 0),
    String(strategyData.threads?.length || 0),
    String(comments.length),
    '0',  // Approved — filled in after QA
    '0',  // Posted — filled in after execution
    String(strategyData.posts?.length || 0),
    '0',  // Posts published — filled in after execution
    String(strategyData.upvotePlan?.totalUpvotes || 0),
    String(brandAlignScore),
    String(redditBPScore),
    (report.riskAssessment?.overallRisk || 'unknown').toUpperCase(),
    'Current month — update after vendor execution',
  ]);
  applyDataStyle(currentRow, trackerCols.length, false);
  currentRow.getCell(1).font = { bold: true, size: 11, name: 'Calibri' };
  currentRow.getCell(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE8F4FD' } };

  // Generate buffer
  const buffer = await wb.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

module.exports = { buildStrategySpreadsheet };
